schema_version = "1.0.0"
id = "EOTATools"
version = "1.0.2"
name = "EOTATools"
tagline = "Create BG Layout"
maintainer = "EOTA, Peakys 加藤宏怜(@hirosaoto654)"
type = "add-on"
website = "https://github.com/peakys-org/BlenderEOTATools-Distribution"
tags = ["3D View", "Render", "Compositing", "Node", "Camera", "Bake"]
blender_version_min = "4.0.0"
license = [
  "Proprietary: All rights reserved by EOTA.",
]
copyright = [
  "2020 EOTA Inc.",
]
